### PR TITLE
Footer changed

### PR DESCRIPTION
**Pull request by sheetalj2205**
## Related Issue
302
- Info about the related issue

Closes: #302 

### Describe the changes you've made
I have changed the footer but not able to find the icon for discord. Please check it.
Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x
footer
] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Comment by pinkman7009** [comment]
can you add some margin between the footer beginning and Contact Us? it would look better.

**Review by Anurag5086 — CHANGES_REQUESTED** [review]
Add only your commits!

**Comment by sheetalj2205** [comment]
Please check this PR

**Comment by msk4862** [comment]
@sheetalj2205 maybe you can use custom svg for discord icon.
@aryasoni98 look into this.

**Review by aryasoni98 — APPROVED** [review]
LGTM

**Review by Anurag5086 — APPROVED** [review]
looks good

**Comment by aryasoni98** [comment]
Screenshot 2021-04-20 at 2 34 53 AM
@sheetalj2205 fix it .

**Comment by sheetalj2205** [comment]
> Screenshot 2021-04-20 at 2 34 53 AM
> 
> @sheetalj2205 fix it .

Sorry! but I didn't understand

**Comment by aryasoni98** [comment]
> > Screenshot 2021-04-20 at 2 34 53 AM
> > @sheetalj2205 fix it .
> 
> Sorry! but I didn't understand. Icons are not visible?
> Hey! @aryasoni98 I have checked it after pulling all changes from the master. Icons are visible to me.

@sheetalj2205 Social Icon not Visible

**Comment by sheetalj2205** [comment]
> > > Screenshot 2021-04-20 at 2 34 53 AM
> > > @sheetalj2205 fix it .
> > 
> > 
> > Sorry! but I didn't understand. Icons are not visible?
> > Hey! @aryasoni98 I have checked it after pulling all changes from the master. Icons are visible to me.
> 
> @sheetalj2205 Social Icon not Visible

@aryasoni98 but when I am running this icons are visible.

**Comment by Anurag5086** [comment]
> Screenshot 2021-04-20 at 2 34 53 AM
> 
> @sheetalj2205 fix it .

image
@aryasoni98 It looks fine on my side.

**Comment by sheetalj2205** [comment]
@aryasoni98 @Anurag5086  Please assign this PR to me.

**Pull request merged**
