### PR TITLE
Fix and Improve Landing Page layout

### PR DESCRIPTION
**Pull request by shamahdotid**
**What does this PR do?**
This PR fix the landing page layout on mobile and small device by fixing the padding and width styling to make it look better.

**Screenshots?**
Here's the visual comparison about before and after fixing the layout on Landing page

#### Before:
<p>

</p>

#### After:
<p>

</p>

### CODE REVIEW

**Review by vipulsnp — CHANGES_REQUESTED** [review]
image
CSS breaks above 800.

**Comment by Shaddamah** [comment]
Whoops, i'd fix that one asap

**Comment by vipulsnp** [comment]
image
Still breaking at some breakpoints. Please check with all the breakpoints that css doesn't break and content is not hidden.
@Shaddamah

**Review by vipulsnp — CHANGES_REQUESTED** [review]
Hiding the input element on smaller devices.

**Comment by irshadjsr21** [comment]
Closing this since the landing page design has been changed.

**Pull request closed without merging**
