### PR TITLE
aligned carousel buttons

### PR DESCRIPTION
**Pull request by N-Shar-ma**
## Related Issue

Closes: #314 

### Describe the changes you've made

added `justify-content: space-around` to the parent div of the buttons, just like it is for mobile view

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 
image
 | 
image
 |

### CODE REVIEW

**Review by aryasoni98 — APPROVED** [review]

**Review by Anurag5086 — APPROVED** [review]
LGTM! 👍

**Review by msk4862 — APPROVED** [review]
Looks good :+1:

**Comment by pinkman7009** [comment]
looks good to me.

**Review by pinkman7009 — APPROVED** [review]

**Comment by msk4862** [comment]
@aryasoni98 we can merge this PR.

**Pull request merged**
