### PR TITLE
navbar added

### PR DESCRIPTION
**Pull request by sheetalj2205**
## Related Issue
303
- Info about the related issue

Closes: #303 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [
navbar
x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Review by Anurag5086 — APPROVED** [review]
Looks good now!

**Review by aryasoni98 — APPROVED** [review]
Nice 👍

**Comment by sheetalj2205** [comment]
Please add correct tag Level3, its not Level 3

**Comment by Anurag5086** [comment]
> Please add correct tag Level3, its not Level 3

👍

**Pull request merged**
