### PR TITLE
Issue#331

### PR DESCRIPTION
**Pull request by srrathi**
## Related Issue

- Info about the related issue

Closes: #331 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot |
ctold

 updated screenshot |
ctnew

### CODE REVIEW

**Review by Anurag5086 — CHANGES_REQUESTED** [review]
@srrathi Its not recommended to use multiple CSS libraries. Stick to one and uninstall others.

**Review by msk4862 — CHANGES_REQUESTED** [review]
@srrathi Remove `react-icons` dependency as well.
`fontawesome` is being used for icons, you can use that only instead.

**Comment by srrathi** [comment]
> @srrathi Remove `react-icons` dependency as well.
> `fontawesome` is being used for icons, you can use that only instead.

okk I'll do that

**Comment by srrathi** [comment]
> @srrathi Its not recommended to use multiple CSS libraries. Stick to one and uninstall others.

okk I'll do that

**Comment by srrathi** [comment]
@Anurag5086  @msk4862 I have removed those libraries. You can check.

**Pull request closed without merging**
