### PR TITLE
feat: 🐋 Added Docker File

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Related Issue

Added Docker file, pushed it to DockerHub

Closes: #290

### Describe the changes you've made

I have added the Dockerfile and its `.dockerignore` updated `node-sass` version and removed `sass`  from `package.json` to avoid warnings while installing through `package.json` and removing errors while building docker image. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

You can run it by pulling it through the [DockerHub](https://hub.docker.com/r/siddhantkhare/codetrophs-frontend) and running it : 

- Pull

```shell
docker pull siddhantkhare/codetrophs-frontend:dev
```

- Run

```shell
docker run -p 3001:3000 siddhantkhare/codetrophs-frontend:dev
```

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
This check is failing just because of Name of the repo. in `package.json`, because name is giving in uppercase :

image

**Comment by Siddhant-K-code** [comment]
@aryasoni98 Please review and Merge!

**Review by msk4862 — CHANGES_REQUESTED** [review]
@Siddhant-K-code I think the value of `NEXT_PUBLIC_BACKEND_BASE_URL` is not set in `.env` file of the docker image.
You can use `https://api.codetrophs.io/` as backend base url.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code I think the value of `NEXT_PUBLIC_BACKEND_BASE_URL` is not set in `.env` file of the docker image.
> You can use `https://api.codetrophs.io/` as backend base url.

Pushed the new docker image, check now.

btw, on : `https://codetrophs.io/`  "Sign in With GitHub is also not working"

**Comment by Siddhant-K-code** [comment]
@msk4862 

image

**Comment by msk4862** [comment]
> @msk4862
> 
> image

@Siddhant-K-code  Yeah, Its fine. Its a POST api url.

**Comment by msk4862** [comment]
imageedit_2_6430535289

@Siddhant-K-code its showing `undefined` now.
Make sure you have changed the value of `NEXT_PUBLIC_BACKEND_BASE_URL` var and used `.env` file correctly.

**Comment by Siddhant-K-code** [comment]
> imageedit_2_6430535289
> 
> @Siddhant-K-code its showing `undefined` now.
> Make sure you have changed the value of `NEXT_PUBLIC_BACKEND_BASE_URL` var and used `.env` file correctly.

i had already build with req. changes.

**Comment by Siddhant-K-code** [comment]
> > @Siddhant-K-code I think the value of `NEXT_PUBLIC_BACKEND_BASE_URL` is not set in `.env` file of the docker image.
> > You can use `https://api.codetrophs.io/` as backend base url.
> 
> Pushed the new docker image, check now.
> 
> btw, on : `https://codetrophs.io/` "Sign in With GitHub" is also not working

@msk4862 look at this!

**Comment by aryasoni98** [comment]
@msk4862 @Anurag5086 @pinkman7009 Review update

**Comment by aryasoni98** [comment]
Review @msk4862 @Anurag5086 @pinkman7009 ASAP!!

**Comment by Siddhant-K-code** [comment]
Idk, what is going on... all things are fine from my end and already pushed to docker hub with backend URL, you want me to add.

**Pull request closed without merging**
