### PR TITLE
add contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #292 
Added  the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
@aryasoni98 have a look!

### CODE REVIEW

**Review by Anurag5086 — APPROVED** [review]
LGTM

**Comment by khareyash05** [comment]
@Anurag5086 could you please add a GSSOC label and a level label to the same?

**Comment by Anurag5086** [comment]
> @Anurag5086 Thank You!
> Could you please add a GSSOC label and a level label to the same?

Alright Sure!

**Comment by khareyash05** [comment]
@Anurag5086 A small request from you . could you pls delete the easy label and add a level label as easy/medium labels arent being counted 
Thank You

**Comment by Anurag5086** [comment]
> @Anurag5086 A small request from you . could you pls delete the easy label and add a level label as easy/medium labels arent being counted
> Thank You

@aryasoni98 Please check this out.

**Pull request merged**
