### PR TITLE
Donate us button center aligned new PR

### PR DESCRIPTION
**Pull request by srrathi**
## Related Issue

- Info about the related issue

Closes: #349

### Describe the changes you've made
Center aligned the donate us button on landing page.

Give a clear description what modifications you have made
Center aligned the donate us button on landing page.
## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot |
donateusold
 updated screenshot |
image

### CODE REVIEW

**Comment by Anurag5086** [comment]
@srrathi Add a screenshot of mobile version as well!

**Comment by srrathi** [comment]
> @srrathi Add a screenshot of mobile version as well!
@Anurag5086 Mobile view Screenshot
image

**Review by msk4862 — CHANGES_REQUESTED** [review]
@srrathi Add bottom margin to the testimonial component.

**Comment by srrathi** [comment]
> @srrathi Add bottom margin to the testimonial component.

I'll But it's looking fine in my machine. Do I still have to add margin.

**Comment by msk4862** [comment]
@srrathi use browser's Dev Tool and try to see homepage in smaller screen sizes, you will know.

**Comment by srrathi** [comment]
> @srrathi use browser's Dev Tool and try to see homepage in smaller screen sizes, you will know.

@msk4862 I've added top margin to footer section along with the screen size in which they are overlapping with footer. As it's not setting with testimonials. But it's working fine and resolving the issue.

**Review by msk4862 — CHANGES_REQUESTED** [review]
@srrathi decrease the value of `margin-top` to `5rem` for mobile screens using an another media query.

**Review by msk4862 — APPROVED** [review]
Looks good to me :+1:

**Review by aryasoni98 — APPROVED** [review]
LGTW

**Pull request merged**
