### PR TITLE
New Footer integrated

### PR DESCRIPTION
**Pull request by srrathi**
## Related Issue

- Info about the related issue

Closes: #350

### Describe the changes you've made

Give a clear description what modifications you have made
Made New footer with about us, T&C and Privacy Policy link in it.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | 
updated screenshot |
image
image

### CODE REVIEW

**Review by msk4862 — CHANGES_REQUESTED** [review]
@srrathi add some padding b/w the icons in mobile screen view.

**Comment by srrathi** [comment]
> @srrathi add some padding b/w the icons in mobile screen view.

@msk4862 Added.
image

**Review by aryasoni98 — APPROVED** [review]
nice 👍

**Review by msk4862 — APPROVED** [review]
Looks good to me :+1:

**Review by pinkman7009 — APPROVED** [review]
looks good to me

**Comment by srrathi** [comment]
@Anurag5086 Is there anything else which I need to change in it.

**Review by Anurag5086 — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
